apiVersion: v1
kind: ServiceAccount
metadata:
 name: tekton-sa
 namespace: diploe2-lunafelipe1997
imagePullSecrets:
 - name: basic-user-pass
 - name: dockerconfig-secret
secrets:
 - name: basic-user-pass
 - name: dockerconfig-secret