apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
 name: hello-world
 namespace: diploe2-lunafelipe1997
spec:
 steps:
   - name: echo
     image: busybox
     script: |
       #!/bin/sh
       echo "Hello, World from Tekton!"