apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-apply
  namespace: diploe2-lunafelipe1997
spec:
  params:
    - name: manifest
      description: "Nombre del deployment a actualizar"
      type: string
    - name: image
      description: "Imagen a usar"
      type: string
      default: "docker.io/aluna1997/whitelist-api:v2"
  steps:
    - name: update-deployment
      image: bitnami/kubectl:latest
      script: |
        DEPLOYMENT_NAME=$(params.manifest)
        IMAGE=$(params.image)
        NAMESPACE=diploe2-lunafelipe1997

        kubectl delete deployment whitelist-api-deployment
        kubectl create deployment whitelist-api-deployment --image='docker.io/aluna1997/whitelist-api:v2'
        echo "----------"
        kubectl get deployment