apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <base64-encoded-value>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-value>
  AWS_DEFAULT_REGION: <base64-encoded-value>