apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{aws-acces-key-id}}
  AWS_SECRET_ACCESS_KEY: {{aws-secret-acces-key}}
  AWS_DEFAULT_REGION: dXMtZWFzdC0y